const BACKEND_BASE_URL = 'http://219.70.195.108:8000/';
const BACKEND_API_URL = BACKEND_BASE_URL + 'api/';

const BACKEND_URL = {}
BACKEND_URL.BASE = 'http://127.0.0.1:8000/'
BACKEND_URL.API = BACKEND_URL.BASE + 'api/'
BACKEND_URL.APIS = {}
BACKEND_URL.APIS.ACGL = BACKEND_URL.API + 'acgl/'
BACKEND_URL.APIS.ACGLS = {}
BACKEND_URL.APIS.ACGLS.ANIME = BACKEND_URL.APIS.ACGL + 'anime/'
BACKEND_URL.APIS.AUTH = BACKEND_URL.API + 'auth/'
BACKEND_URL.APIS.AUTHS = {}
BACKEND_URL.APIS.AUTHS.REGISTER = BACKEND_URL.APIS.AUTH + 'register/'
BACKEND_URL.APIS.AUTHS.LOGIN = BACKEND_URL.APIS.AUTH + 'login/'
BACKEND_URL.APIS.AUTHS.TOKEN = BACKEND_URL.APIS.AUTH + 'token/'
BACKEND_URL.APIS.AUTHS.TOKENS = {}
BACKEND_URL.APIS.AUTHS.TOKENS.REFRESH = BACKEND_URL.APIS.AUTHS.TOKEN + 'refresh/'

export {
    BACKEND_URL,
    BACKEND_BASE_URL,
    BACKEND_API_URL,
}